import {afterEach,it,expect,vi} from 'vitest';
import {createStore} from '@composable-svelte/core';
import {voiceInputReducer} from '../src/lib/voice-input/reducer.js';
import {createInitialVoiceInputState,type VoiceInputState,type VoiceInputAction,type VoiceInputDependencies} from '../src/lib/voice-input/types.js';
import {AudioManager} from '../src/lib/voice-input/audio/audio-manager.js';
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(error:unknown)=>void;const promise=new Promise<T>((ok,no)=>{resolve=ok;reject=no});return{promise,resolve,reject};}
class Device extends AudioManager {
 liveRecording=false;
 permission=deferred<MediaStream>();
 stopResult:Promise<Blob>|undefined;
 override requestMicrophone=vi.fn(()=>this.permission.promise);
 override startRecording=vi.fn(()=>{this.liveRecording=true;});
 override stopRecording=vi.fn(()=>{this.liveRecording=false;return this.stopResult??Promise.resolve(new Blob(['voice']));});
 override startAudioLevelMonitoring=vi.fn(()=>1);
 override stopInterval=vi.fn();
 override detectVoiceActivity=vi.fn(()=>false);
 override cleanup=vi.fn(()=>{this.liveRecording=false;});
}
const cleanups:Array<()=>void>=[];
afterEach(()=>{cleanups.splice(0).reverse().forEach(fn=>fn());vi.useRealTimers();});
const checkpoint=()=>new Promise<void>(resolve=>setTimeout(resolve,0));
function setup(overrides:Partial<VoiceInputState>={},managed=false){
 const device=new Device();const pending:Array<ReturnType<typeof deferred<string>>>=[];
 const dependencies:VoiceInputDependencies={getAudioManager:()=>device,transcribeAudio:vi.fn(()=>{const d=deferred<string>();pending.push(d);return d.promise;})};
 const store=createStore<VoiceInputState,VoiceInputAction,VoiceInputDependencies>({initialState:{...createInitialVoiceInputState(),permission:'granted',_audioManagerId:'device',...overrides},reducer:voiceInputReducer,dependencies,...(managed?{execution:{mode:'managed' as const}}:{}),ssr:{deferEffects:false}});
 const transcripts:string[]=[];store.subscribeToActions?.(action=>{if(action.type==='transcriptionCompleted')transcripts.push(action.transcript);});cleanups.push(()=>store.destroy());return{store,device,pending,dependencies,transcripts};
}
it('holds processing through transcription and publishes one accepted terminal',async()=>{const {store,pending,transcripts}=setup();store.dispatch({type:'startPushToTalkRecording'});store.dispatch({type:'stopPushToTalkRecording'});await checkpoint();expect(pending).toHaveLength(1);expect(store.state.status).toBe('processing');pending[0]!.resolve('accepted');await checkpoint();expect(store.state.status).toBe('idle');expect(transcripts).toEqual(['accepted']);});
it('transcription failure stops restarted conversation recorder while retaining device',async()=>{const {store,device,pending}=setup();store.dispatch({type:'activateConversationMode'});store.dispatch({type:'manualSendRequested'});await checkpoint();expect(device.liveRecording).toBe(true);expect(device.startRecording).toHaveBeenCalledTimes(2);pending[0]!.reject(new Error('transcription failed'));await checkpoint();expect(store.state.status).toBe('error');expect(device.liveRecording).toBe(false);expect(device.cleanup).not.toHaveBeenCalled();});
it('switching to push mode retires VAD and clears its state without starting a recorder',async()=>{vi.useFakeTimers();const {store,device}=setup();store.dispatch({type:'activateConversationMode'});await vi.advanceTimersByTimeAsync(100);expect(device.detectVoiceActivity).toHaveBeenCalled();const polls=device.detectVoiceActivity.mock.calls.length;store.dispatch({type:'activatePushToTalk'});expect(store.state.vadState).toBeNull();await vi.advanceTimersByTimeAsync(1000);expect(device.detectVoiceActivity).toHaveBeenCalledTimes(polls);expect(device.liveRecording).toBe(false);expect(store.state.mode).toBe('push-to-talk');});
it('permission reduction is repeatable and does not allocate device IDs',()=>{const state=createInitialVoiceInputState();const deps:VoiceInputDependencies={getAudioManager:()=>undefined,transcribeAudio:async()=>''};const first=voiceInputReducer(state,{type:'requestMicrophonePermission'},deps)[0];const second=voiceInputReducer(state,{type:'requestMicrophonePermission'},deps)[0];expect(second).toEqual(first);});
it('cancelling a pending permission request prevents late grant from starting recording',async()=>{const device=new Device();const registry=new Map<string,AudioManager>();const deps:VoiceInputDependencies={getAudioManager:id=>registry.get(id),createAudioManager:id=>{registry.set(id,device);return device;},deleteAudioManager:id=>{registry.get(id)?.cleanup();registry.delete(id);},transcribeAudio:async()=>''};const store=createStore({initialState:createInitialVoiceInputState(),reducer:voiceInputReducer,dependencies:deps,ssr:{deferEffects:false}});cleanups.push(()=>store.destroy());store.dispatch({type:'startPushToTalkRecording'});expect(store.state.status).toBe('requesting-permission');store.dispatch({type:'cancelPushToTalkRecording'});device.permission.resolve({} as MediaStream);await checkpoint();expect(store.state.status).toBe('idle');expect(device.startRecording).not.toHaveBeenCalled();expect(registry.size).toBe(0);});
it.each(['success','failure'] as const)('older transcription %s cannot affect a newer recording',async outcome=>{const {store,pending,device,transcripts}=setup();store.dispatch({type:'startPushToTalkRecording'});store.dispatch({type:'stopPushToTalkRecording'});await checkpoint();store.dispatch({type:'startPushToTalkRecording'});expect(store.state.status).toBe('recording');if(outcome==='success')pending[0]!.resolve('old');else pending[0]!.reject(new Error('old failure'));await checkpoint();expect(store.state.status).toBe('recording');expect(device.liveRecording).toBe(true);expect(transcripts).toEqual([]);});
it('late stop result after deactivation never restarts conversation recording',async()=>{const {store,device,transcripts}=setup();const stop=deferred<Blob>();device.stopResult=stop.promise;store.dispatch({type:'activateConversationMode'});store.dispatch({type:'manualSendRequested'});store.dispatch({type:'deactivateVoiceInput'});stop.resolve(new Blob(['old']));await checkpoint();expect(store.state.status).toBe('idle');expect(device.startRecording).toHaveBeenCalledTimes(1);expect(transcripts).toEqual([]);});
it('duplicate stop cannot schedule two transcriptions',async()=>{const {store,device,pending}=setup();const stop=deferred<Blob>();device.stopResult=stop.promise;store.dispatch({type:'startPushToTalkRecording'});store.dispatch({type:'stopPushToTalkRecording'});store.dispatch({type:'stopPushToTalkRecording'});expect(device.stopRecording).toHaveBeenCalledTimes(1);stop.resolve(new Blob());await checkpoint();expect(pending).toHaveLength(1);pending[0]!.resolve('one');await checkpoint();});
it('recording reduction does not sample the clock or start hardware',()=>{const device=new Device();const dependencies:VoiceInputDependencies={getAudioManager:()=>device,transcribeAudio:async()=>''};const state={...createInitialVoiceInputState(),permission:'granted' as const,_audioManagerId:'device'};const now=vi.spyOn(Date,'now');try{for(const type of ['startPushToTalkRecording','activateConversationMode'] as const){const a=voiceInputReducer(state,{type},dependencies)[0];const b=voiceInputReducer(state,{type},dependencies)[0];expect(a).toEqual(b);}expect(now).not.toHaveBeenCalled();expect(device.startRecording).not.toHaveBeenCalled();}finally{now.mockRestore();}});
it('independent stores acquire distinct registry IDs and retiring one preserves the other',async()=>{const registry=new Map<string,Device>();const deps:VoiceInputDependencies={getAudioManager:id=>registry.get(id),createAudioManager:id=>{const device=new Device();registry.set(id,device);return device;},deleteAudioManager:id=>{registry.get(id)?.cleanup();registry.delete(id);},transcribeAudio:async()=>''};const make=()=>createStore({initialState:createInitialVoiceInputState(),reducer:voiceInputReducer,dependencies:deps,ssr:{deferEffects:false}});const first=make(),second=make();cleanups.push(()=>first.destroy(),()=>second.destroy());first.dispatch({type:'startPushToTalkRecording'});second.dispatch({type:'startPushToTalkRecording'});expect(first.state._audioManagerId).not.toBe(second.state._audioManagerId);expect(registry.size).toBe(2);const live=registry.get(second.state._audioManagerId!)!;first.dispatch({type:'cancelPushToTalkRecording'});live.permission.resolve({} as MediaStream);await checkpoint();expect(live.startRecording).toHaveBeenCalledOnce();expect(second.state.status).toBe('recording');expect(registry.size).toBe(1);});
it('conversation accepts distinct overlapping utterances once even when responses arrive out of order',async()=>{const {store,pending,transcripts}=setup();store.dispatch({type:'activateConversationMode'});store.dispatch({type:'manualSendRequested'});await checkpoint();store.dispatch({type:'manualSendRequested'});await checkpoint();expect(pending).toHaveLength(2);pending[1]!.resolve('second');await checkpoint();pending[0]!.resolve('first');await checkpoint();expect(transcripts).toEqual(['second','first']);expect(store.state.mode).toBe('conversation');expect(store.state._pendingTranscriptions).toEqual([]);});
it.each(['deactivate','destroy'] as const)('retired transcription cannot notify after %s',async termination=>{const {store,pending,transcripts,dependencies}=setup();store.dispatch({type:'startPushToTalkRecording'});store.dispatch({type:'stopPushToTalkRecording'});await checkpoint();expect(dependencies.transcribeAudio).toHaveBeenCalledOnce();if(termination==='destroy')store.destroy();else store.dispatch({type:'deactivateVoiceInput'});pending[0]!.resolve('retired');await checkpoint();expect(transcripts).toEqual([]);});
it('initial quiet polls never send, while speech followed by silence sends one utterance',async()=>{vi.useFakeTimers();const {store,device,pending}=setup();store.dispatch({type:'activateConversationMode'});await vi.advanceTimersByTimeAsync(4000);expect(store.state.vadState?.silenceDuration).toBe(0);expect(device.stopRecording).not.toHaveBeenCalled();expect(pending).toHaveLength(0);device.detectVoiceActivity.mockReturnValue(true);await vi.advanceTimersByTimeAsync(100);expect(store.state.vadState?.isSpeaking).toBe(true);device.detectVoiceActivity.mockReturnValue(false);await vi.advanceTimersByTimeAsync(4000);expect(device.stopRecording).toHaveBeenCalledOnce();expect(pending).toHaveLength(1);expect(store.state.vadState?.silenceDuration).toBe(0);});
it('duplicate conversation activation during a pending stop preserves the utterance',async()=>{const {store,device,pending}=setup();const stopped=deferred<Blob>();device.stopResult=stopped.promise;store.dispatch({type:'activateConversationMode'});store.dispatch({type:'manualSendRequested'});const generation=store.state._generation;store.dispatch({type:'activateConversationMode'});expect(store.state._generation).toBe(generation);stopped.resolve(new Blob());await checkpoint();expect(pending).toHaveLength(1);});
it('permission requested after selecting push mode does not itself start recording',async()=>{const device=new Device();const registry=new Map<string,AudioManager>();const dependencies:VoiceInputDependencies={getAudioManager:id=>registry.get(id),createAudioManager:id=>{registry.set(id,device);return device;},deleteAudioManager:id=>{registry.get(id)?.cleanup();registry.delete(id);},transcribeAudio:async()=>''};const store=createStore({initialState:createInitialVoiceInputState(),reducer:voiceInputReducer,dependencies,ssr:{deferEffects:false}});cleanups.push(()=>store.destroy());store.dispatch({type:'activatePushToTalk'});store.dispatch({type:'requestMicrophonePermission'});device.permission.resolve({} as MediaStream);await checkpoint();expect(store.state.mode).toBe('push-to-talk');expect(store.state.status).toBe('ready');expect(device.startRecording).not.toHaveBeenCalled();});
it('completed push-to-talk transcription preserves selected mode',async()=>{const {store,pending}=setup();store.dispatch({type:'startPushToTalkRecording'});store.dispatch({type:'stopPushToTalkRecording'});await checkpoint();pending[0]!.resolve('spoken');await checkpoint();expect(store.state.mode).toBe('push-to-talk');expect(store.state.status).toBe('idle');});

it('managed voice assembly installs effects before a subscriber cancellation turn',()=>{const {store,device}=setup({},true);let cancelled=false;store.subscribe(state=>{if(state.status==='recording'&&!cancelled){cancelled=true;store.dispatch({type:'cancelPushToTalkRecording'});}});store.dispatch({type:'startPushToTalkRecording'});expect(store.state.status).toBe('idle');expect(device.liveRecording).toBe(false);});
