import {run} from '../probes/harness.mjs';
const sv = (script, tpl) => ({'App.svelte': `<script lang="ts">\n${script}\n</script>\n${tpl}\n`});
run([
  ['F1 each no as', sv(`const xs = [1, 2];`, `{#each xs}<p>x</p>{/each}`)],
  ['F2 each no as, index', sv(`const xs = [1, 2];`, `{#each xs, i}<p>{i}</p>{/each}`)],
  ['F3 each as, idx, key', sv(`const xs = [{id: 1}];`, `{#each xs as x, i (x.id)}<p>{i}</p>{/each}`)],
  ['F4 each typed ctx', sv(`const xs = [{id: 1}];`, `{#each xs as x: any}<p>{x.id}</p>{/each}`)],
  ['F5 each paren expr', sv(`const xs = [{id: 1}];`, `{#each (xs) as x}<p>{x.id}</p>{/each}`)],
  ['F6 each else', sv(`const xs: any[] = [];`, `{#each xs as x}<p>{x}</p>{:else}<p>none</p>{/each}`)],
  ['F7 await no then', sv(`const p = Promise.resolve(1);`, `{#await p}<p>..</p>{/await}`)],
  ['F8 await then short', sv(`const p = Promise.resolve(1);`, `{#await p then}<p>ok</p>{/await}`)],
  ['F9 await :then no value', sv(`const p = Promise.resolve(1);`, `{#await p}<p>..</p>{:then}<p>ok</p>{/await}`)],
  ['F10 await :then v empty', sv(`const p = Promise.resolve(1);`, `{#await p}{:then v}{/await}`)],
  ['F11 await then v empty', sv(`const p = Promise.resolve(1);`, `{#await p then v}{/await}`)],
  ['F12 await catch only', sv(`const p = Promise.resolve(1);`, `{#await p catch e}<p>{String(e)}</p>{/await}`)],
  ['F13 const typed', sv(`const o = {a: 1};`, `{#if true}{@const a: number = o.a}<p>{a}</p>{/if}`)],
  ['F14 const satisfies', sv(`const o = {a: 1};`, `{#if true}{@const a = o.a as number}<p>{a}</p>{/if}`)],
  ['F15 const in each', sv(`const xs = [{a: 1}];`, `{#each xs as x}{@const d = x.a * 2}<p>{d}</p>{/each}`)],
  ['F16 each string', sv(`const s = 'abc';`, `{#each s as ch}<p>{ch}</p>{/each}`)],
  ['F17 each Array(n)', sv(``, `{#each Array(3) as _, i}<p>{i}</p>{/each}`)],
  ['F18 each new Array', sv(``, `{#each new Array(3) as _, i}<p>{i}</p>{/each}`)],
  ['F19 each Array.from', sv(``, `{#each Array.from({length: 3}) as _, i}<p>{i}</p>{/each}`)],
  ['F20 each {length}', sv(``, `{#each {length: 3} as _, i}<p>{i}</p>{/each}`)],
  ['F21 each keys spread', sv(``, `{#each [...Array(3).keys()] as i}<p>{i}</p>{/each}`)],
  ['F22 each Object.keys', sv(`const o = {a: 1};`, `{#each Object.keys(o) as k}<p>{k}</p>{/each}`)],
  ['F23 each entries', sv(`const o = {a: 1};`, `{#each Object.entries(o) as [k, v]}<p>{k}{v}</p>{/each}`)],
  ['F24 each map/filter', sv(`const xs = [1, 2];`, `{#each xs.filter((x) => x > 1).map((x) => ({x})) as {x}}<p>{x}</p>{/each}`)],
  ['F25 each split', sv(`const s = 'a,b';`, `{#each s.split(',') as p}<p>{p}</p>{/each}`)],
  ['F26 each props', sv(`let {items = []}: {items?: {n: number}[]} = $props();`, `{#each items as it (it.n)}<p>{it.n}</p>{/each}`)],
  ['F27 each derived', sv(`let s = $state([1, 2]);\nconst d = $derived(s.map((x) => x * 2));`, `{#each d as x}<p>{x}</p>{/each}`)],
  ['F28 each ?? []', sv(`const o: {xs?: number[]} = {};`, `{#each o.xs ?? [] as x}<p>{x}</p>{/each}`)],
  ['F29 each local fn range', sv(`function range(n: number) { return Array.from({length: n}, (_, i) => i); }`, `{#each range(3) as i}<p>{i}</p>{/each}`)],
  ['F30 each Map entries', sv(`const m = new Map([[1, 'a']]);`, `{#each [...m.entries()] as [k, v]}<p>{k}{v}</p>{/each}`)],
  ['F31 each Map direct', sv(`const m = new Map([[1, 'a']]);`, `{#each m as [k, v]}<p>{k}{v}</p>{/each}`)],
  ['F32 each sort copy', sv(`const xs = [3, 1];`, `{#each [...xs].sort() as x}<p>{x}</p>{/each}`)],
  ['F33 then fetch-free async', sv(`async function load() { return [{n: 1}]; }`, `{#await load() then rows}{#each rows as r}<p>{r.n}</p>{/each}{/await}`)],
  ['F34 then props promise', sv(`let {p}: {p: Promise<{n: number}>} = $props();`, `{#await p then {n}}<p>{n}</p>{/await}`)],
  ['F35 each nested const', sv(`const g = [{rows: [{n: 1}]}];`, `{#each g as grp}{#each grp.rows as r, j}{@const label = grp.rows.length + r.n + j}<p>{label}</p>{/each}{/each}`)],
  ['F36 each in snippet', sv(``, `{#snippet list(rows: {n: number}[])}{#each rows as r}<p>{r.n}</p>{/each}{/snippet}\n{@render list([{n: 1}])}`)],
  ['F37 each SvelteMap', sv(`import {SvelteMap} from 'svelte/reactivity';\nconst m = new SvelteMap([[1, 'a']]);`, `{#each m as [k, v]}<p>{k}{v}</p>{/each}`)],
  ['F38 each Date array', sv(`const ds = [new Date()];`, `{#each ds as d}<p>{d.toISOString()}</p>{/each}`)],
  ['F39 each JSON.parse', sv(`const xs = JSON.parse('[1]');`, `{#each xs as x}<p>{x}</p>{/each}`)],
  ['F40 const Math', sv(`const xs = [1];`, `{#if true}{@const m = Math.max(...xs)}<p>{m}</p>{/if}`)],
  ['F41 const Intl fmt', sv(``, `{#if true}{@const f = new Intl.NumberFormat('en')}<p>{f.format(1)}</p>{/if}`)],
  ['F42 each $state class', sv(`class Todo { done = $state(false); text = 'a'; }\nconst todos = $state([new Todo()]);`, `{#each todos as t}<input type="checkbox" bind:checked={t.done} /><p>{t.text}</p>{/each}`)],
  ['F43 each bind item', sv(`let rows = $state([{v: 'a'}]);`, `{#each rows as row}<input bind:value={row.v} />{/each}`)],
]);
