import {it,expect,vi} from 'vitest';
import {mount,unmount,tick} from 'svelte';
import Fixture from './fixtures/ApplicationNested.svelte';
import {scopeTo,optionalSlot,type ApplicationInstance,type ChildView} from '../src/lib/application/index.js';
import {workspaceSlot,nestedEditor,type Root,type Action,type Leaf,type LeafAction} from './fixtures/ApplicationNestedModel.js';
function setup(count=0,step=2){const target=document.createElement('div');document.body.append(target);const trace:string[]=[];const views:(ChildView<Leaf,LeafAction>|undefined)[]=[];let app!:ApplicationInstance<Root,Action>;const component=mount(Fixture,{target,props:{count,dependencies:{step,trace},onApp:value=>app=value,onView:view=>views.push(view)}});return{target,trace,views,component,app};}
it('nested typed views reduce exactly once and separate roots',async()=>{const a=setup(1,3),b=setup(10,7);await tick();a.target.querySelector('button')!.click();await tick();expect(a.target.textContent).toBe('4');expect(b.target.textContent).toBe('10');expect(a.trace).toEqual(['leaf','workspace','root']);expect(b.trace).toEqual([]);await unmount(a.component);await unmount(b.component);a.target.remove();b.target.remove();});
it('rebinds identical-state replaced owners and drops retained handlers',async()=>{const a=setup();await tick();const old=a.views.at(-1)!;const same=a.app.store.state;const notifications:Root[]=[];const off=a.app.store.subscribe(state=>notifications.push(state));a.app.store.dispatch({type:'replaceRoot'});expect(a.app.store.state).toBe(same);await tick();const replacement=a.views.at(-1)!;expect(replacement).not.toBe(old);expect(old.state).toBeUndefined();expect(notifications).toEqual([same]);a.trace.length=0;old.dispatch({type:'increment'});expect(a.trace).toEqual([]);a.target.querySelector('button')!.click();await tick();expect(a.target.textContent).toBe('2');expect(a.trace).toEqual(['leaf','workspace','root']);off();await unmount(a.component);a.target.remove();});
it('keeps binding identity for surviving owners and observes absence, reopening, retirement',async()=>{const a=setup();await tick();const old=a.views.at(-1)!;a.app.store.dispatch({type:'noop'});await tick();expect(a.views).toHaveLength(1);a.app.store.dispatch({type:'close'});await tick();expect(a.target.textContent).toBe('absent');expect(a.views.at(-1)).toBeUndefined();a.app.store.dispatch({type:'open'});await tick();expect(a.views.at(-1)).not.toBe(old);old.dispatch({type:'increment'});expect(a.target.textContent).toBe('0');const latest=a.views.at(-1)!;await unmount(a.component);expect(latest.state).toBeUndefined();latest.dispatch({type:'increment'});expect(a.app.store.state.workspace?.editor?.count).toBe(0);a.target.remove();});
it('rejects foreign same-schema tokens and missing composition metadata',async()=>{const a=setup();await tick();expect(()=>scopeTo(a.app.store,optionalSlot<Root,Action>()('workspace'))).toThrow('not registered');expect(()=>scopeTo({...a.app.store},nestedEditor)).toThrow('managed composition');expect(()=>Reflect.apply(scopeTo,undefined,[a.app.store])).toThrow('typed slot token');await unmount(a.component);a.target.remove();});
it('rejects pre-Host scoped authority but permits descendant setup and later detachment',async()=>{const target=document.createElement('div');document.body.append(target);expect(()=>mount(Fixture,{target,props:{dependencies:{step:1,trace:[]},onApp:app=>scopeTo(app.store,nestedEditor)}})).toThrow('first ApplicationHost');target.remove();const a=setup();await tick();const view=scopeTo(a.app.store,nestedEditor)!;a.component.hide();await tick();view.dispatch({type:'increment'});a.component.show();await tick();expect(a.target.textContent).toBe('2');await unmount(a.component);a.target.remove();const other=document.createElement('div');document.body.append(other);const c=mount(Fixture,{target:other,props:{dependencies:{step:4,trace:[]},incrementOnSetup:true}});expect(other.textContent).toBe('4');await unmount(c);other.remove();});

it('nested replacement preserves leaf identity while retiring the old projection',async()=>{const a=setup();await tick();const old=a.views.at(-1)!;const leaf=old.state;const terminal:(Leaf|undefined)[]=[];const off=old.subscribe(value=>terminal.push(value));a.app.store.dispatch(workspaceSlot.wrap({type:'replaceEditor'}));await tick();expect(a.views.at(-1)?.state).toBe(leaf);expect(a.views.at(-1)).not.toBe(old);expect(terminal).toEqual([leaf,undefined]);off();await unmount(a.component);a.target.remove();});
import {hydrate} from 'svelte';
import markup from './fixtures/application-scoping-ssr.html?raw';
it('hydrates actual server nested markup and attaches scoped actions without mismatch',async()=>{const target=document.createElement('div');document.body.append(target);target.innerHTML=markup;const original=target.querySelector('button');const trace:string[]=[];const component=hydrate(Fixture,{target,props:{count:3,dependencies:{step:3,trace}}});await tick();expect(target.querySelector('button')).toBe(original);expect(trace).toEqual([]);target.querySelector('button')!.click();await tick();expect(target.textContent).toBe('6');expect(trace).toEqual(['leaf','workspace','root']);await unmount(component);target.remove();});
import Observer from './fixtures/ApplicationViewObserver.svelte';
it('invalidates an independently mounted view when its application root is destroyed',async()=>{const a=setup(5);await tick();const observerTarget=document.createElement('div');document.body.append(observerTarget);const observer=mount(Observer,{target:observerTarget,props:{view:a.views.at(-1)!}});expect(observerTarget.textContent).toBe('5');await unmount(a.component);await tick();expect(observerTarget.textContent).toBe('retired');await unmount(observer);observerTarget.remove();a.target.remove();});

it('child subscriptions stay silent when only ancestor state is reconstructed',async()=>{const a=setup();await tick();const view=a.views.at(-1)!;const values:(Leaf|undefined)[]=[];const off=view.subscribe(value=>values.push(value));const before=a.app.store.state;a.app.store.dispatch(workspaceSlot.wrap({type:'touch'}));expect(a.app.store.state).not.toBe(before);expect(values).toEqual([view.state]);view.dispatch({type:'increment'});expect(values.map(value=>value?.count)).toEqual([0,2]);a.app.store.dispatch({type:'close'});expect(values.map(value=>value?.count)).toEqual([0,2,undefined]);off();await unmount(a.component);a.target.remove();});

it('observes async subscriber rejection while preserving unchanged-value filtering',async()=>{const a=setup();await tick();const error=new Error('subscriber rejection');const report=vi.spyOn(console,'error').mockImplementation(()=>{});const view=a.views.at(-1)!;const stop=view.subscribe(async()=>{throw error;});try{await Promise.resolve();await Promise.resolve();expect(report).toHaveBeenCalledTimes(1);expect(report.mock.calls[0]?.[1]).toBe(error);a.app.store.dispatch(workspaceSlot.wrap({type:'touch'}));await Promise.resolve();expect(report).toHaveBeenCalledTimes(1);}finally{stop();report.mockRestore();await unmount(a.component);a.target.remove();}});
