import type {FeatureView} from '../src/lib/application/index.js';
import type {SlotCatalog} from '../src/lib/navigation/managed-integration.js';
import {it,expect,vi} from 'vitest';import {mount,unmount,tick} from 'svelte';
import Fixture from './fixtures/FeatureViewsApp.svelte';import Raw from './fixtures/FeatureViewsRaw.svelte';
import {defineViews,FeatureOutlet,ManagedIntegrationBuilder,optionalSlot,type ApplicationInstance} from '../src/lib/application/index.js';
import {createStore} from '../src/lib/store.svelte.js';import {Effect} from '../src/lib/effect.js';import type {Reducer} from '../src/lib/types.js';
import {composition,initial,events,captured,retainedNestedViews,workspaceComposition,workspaceSlot,workerSlot,rowsSlot,startupApplication,leaf,type Root,type Action,type Deps,type WorkspaceView} from './fixtures/FeatureViewsModel.js';
import {rootViews,workspaceViews} from './fixtures/FeatureViewsPlans.js';import Leaf from './fixtures/FeatureViewsLeaf.svelte';import Workspace from './fixtures/FeatureViewsWorkspace.svelte';
function mountView<S,A,C extends SlotCatalog>(view:FeatureView<S,A,C>,target:Element){return mount(FeatureOutlet<S,A,C>,{target,props:{view}});}
function setup(count=0){events.length=0;captured.length=0;const target=document.createElement('div');document.body.append(target);const trace:string[]=[];let app!:ApplicationInstance<Root,Action>;const component=mount(Fixture,{target,props:{count,dependencies:{step:3,trace},onApp:value=>app=value}});return{target,trace,app,component};}
function leafNode(target:Element,name:string){return target.querySelector(`[data-leaf="${name}"]`)!;}
function click(target:Element,name:string,action='increment'){(leafNode(target,name).querySelector(`[data-action="${action}"]`) as HTMLButtonElement).click();}
it('renders exhaustive nested and collection plans, with explicit headless capability and exact reduction',async()=>{const a=setup(2);await tick();expect(a.target.querySelectorAll('[data-leaf]')).toHaveLength(3);expect(a.target.querySelector('[data-leaf="worker"]')).toBeNull();expect(events).toEqual(['mount:editor','mount:row1','mount:row2']);click(a.target,'editor');await tick();expect(leafNode(a.target,'editor').textContent).toBe('50');expect(a.trace).toEqual(['editor','workspace','root']);await unmount(a.component);expect(events.filter(x=>x.startsWith('destroy:'))).toHaveLength(3);a.target.remove();});
it('remounts same-state replaced owner and drops the previous component handler',async()=>{const a=setup();await tick();const old=captured.find(view=>view.state?.name==='editor')!;const node=leafNode(a.target,'editor');click(a.target,'editor','local');await tick();expect(node.textContent).toBe('01');const state=a.app.store.state;a.app.store.dispatch({type:'replace'});expect(a.app.store.state).toBe(state);await tick();expect(leafNode(a.target,'editor')).not.toBe(node);expect(leafNode(a.target,'editor').textContent).toBe('00');expect(events.filter(x=>x==='mount:editor')).toHaveLength(2);expect(events.filter(x=>x==='destroy:editor')).toHaveLength(1);a.trace.length=0;old.dispatch({type:'increment'});expect(a.trace).toEqual([]);click(a.target,'editor');await tick();expect(leafNode(a.target,'editor').textContent).toBe('30');await unmount(a.component);a.target.remove();});
it('preserves keyed survivors across edits/reorder, but retires removed/reused and explicitly replaced keys',async()=>{const a=setup();await tick();const original=leafNode(a.target,'row1');const old=captured.find(view=>view.state?.name==='row1')!;click(a.target,'row1','local');a.app.store.dispatch({type:'reorder'});await tick();expect(leafNode(a.target,'row1')).toBe(original);expect(original.textContent).toBe('11');click(a.target,'row1');await tick();expect(leafNode(a.target,'row1')).toBe(original);expect(original.textContent).toBe('41');a.app.store.dispatch({type:'replaceRow'});await tick();expect(leafNode(a.target,'row1')).not.toBe(original);expect(leafNode(a.target,'row1').textContent).toBe('40');a.app.store.dispatch({type:'removeRow'});await tick();expect(a.target.querySelector('[data-leaf="row1"]')).toBeNull();a.app.store.dispatch({type:'addRow'});await tick();old.dispatch({type:'increment'});expect(leafNode(a.target,'row1').textContent).toBe('00');await unmount(a.component);a.target.remove();});
it('works independently with a raw managed Store and no ApplicationHost',async()=>{const target=document.createElement('div');document.body.append(target);const trace:string[]=[];const store=createStore({initialState:initial(9),...composition,dependencies:{step:2,trace}});const component=mount(Raw,{target,props:{store}});await tick();click(target,'editor');await tick();expect(leafNode(target,'editor').textContent).toBe('110');expect(trace).toEqual(['editor','workspace','root']);await unmount(component);store.destroy();target.remove();});
it('rejects dynamic missing/extra/foreign nested mappings without starting a feature',()=>{const forged=(input:unknown)=>Reflect.apply(defineViews,undefined,[composition,input]);expect(()=>forged({})).toThrow('Every composed slot');expect(()=>forged({workspace:{headless:true},worker:{headless:true},rows:{headless:true},extra:{headless:true}})).toThrow('Every composed slot');expect(()=>forged({workspace:{render:Workspace,children:rootViews},worker:{headless:true},rows:{render:Leaf}})).toThrow('exact child');const base:Reducer<Root,Action,Deps>=state=>[state,Effect.none()];const mutable=new ManagedIntegrationBuilder(base);mutable.with(workspaceSlot,workspaceComposition);expect(()=>defineViews(mutable.build(),{})).toThrow('Every composed slot');expect(()=>forged({workspace:{render:Workspace,children:workspaceViews},worker:{headless:true,render:Leaf},rows:{render:Leaf}})).toThrow('rendering mode');});
import SnippetFixture from './fixtures/FeatureViewsSnippet.svelte';
it('supports consumer markup snippets with typed captured child actions',async()=>{const target=document.createElement('div');document.body.append(target);const trace:string[]=[];const store=createStore({initialState:initial(0),...composition,dependencies:{step:5,trace}});const component=mount(SnippetFixture,{target,props:{store}});await tick();expect(target.querySelectorAll('button')).toHaveLength(2);(target.querySelector('[data-snippet="row1"]') as HTMLButtonElement).click();await tick();expect(target.querySelector('[data-snippet="row1"]')?.textContent).toBe('6');expect(trace).toEqual(['row1','root']);await unmount(component);store.destroy();target.remove();});

import {hydrate} from 'svelte';import html from './fixtures/feature-views-ssr.html?raw';
it('hydrates real SSR nested markup without replacing server nodes, then remounts accepted owner replacement',async()=>{events.length=0;captured.length=0;const target=document.createElement('div');document.body.append(target);target.innerHTML=html;const original=leafNode(target,'editor');let app!:ApplicationInstance<Root,Action>;const component=hydrate(Fixture,{target,props:{count:3,dependencies:{step:2,trace:[]},onApp:value=>app=value}});await tick();expect(leafNode(target,'editor')).toBe(original);expect(events.filter(x=>x==='mount:editor')).toHaveLength(1);app.store.dispatch({type:'replace'});await tick();expect(leafNode(target,'editor')).not.toBe(original);await unmount(component);target.remove();});
it('rejects same-schema foreign plans before startup or any leaf mounts, including all-headless mappings',()=>{events.length=0;captured.length=0;const core:Reducer<Root,Action,Deps>=state=>[state,Effect.none()];const foreign=new ManagedIntegrationBuilder(core).with(workspaceSlot,workspaceComposition).with(workerSlot,leaf).forEach(rowsSlot,leaf).build();const plan=defineViews(foreign,{workspace:{headless:true},worker:{headless:true},rows:{headless:true}});const target=document.createElement('div');document.body.append(target);const trace:string[]=[];let app!:ApplicationInstance<Root,Action>;expect(()=>mount(Fixture,{target,props:{plan,definition:startupApplication,dependencies:{step:1,trace},onApp:value=>app=value}})).toThrow('does not belong');expect(trace).toEqual([]);expect(events).toEqual([]);expect(captured).toEqual([]);const warning=vi.spyOn(console,'warn').mockImplementation(()=>{});try{app.store.dispatch({type:'boot'});expect(trace).toEqual([]);}finally{warning.mockRestore();target.remove();}});

it('retained nested outlet descriptors cannot reacquire a replacement parent lifetime',async()=>{retainedNestedViews.length=0;const a=setup();await tick();const old=retainedNestedViews[0]!;a.app.store.dispatch({type:'replace'});await tick();const mountCount=events.length;const target=document.createElement('div');document.body.append(target);expect(resolveView(old)).toEqual([]);expect(()=>mountView(old,target)).toThrow('requires its declared FeatureViews layout');expect(target.querySelector('[data-leaf]')).toBeNull();expect(events).toHaveLength(mountCount);await unmount(a.component);a.target.remove();target.remove();});
it('repeated owner replacement keeps one live subtree and balances every mounted lifetime',async()=>{const a=setup();await tick();for(let i=0;i<100;i++){a.app.store.dispatch({type:'replace'});await tick();expect(a.target.querySelectorAll('[data-leaf]')).toHaveLength(3);}expect(events.filter(x=>x==='mount:editor')).toHaveLength(101);expect(events.filter(x=>x==='destroy:editor')).toHaveLength(100);expect(events.filter(x=>x==='mount:row1')).toHaveLength(1);expect(events.filter(x=>x==='destroy:row1')).toHaveLength(0);await unmount(a.component);expect(events.filter(x=>x==='mount:editor')).toHaveLength(events.filter(x=>x==='destroy:editor').length);expect(events.filter(x=>x==='mount:row1')).toHaveLength(events.filter(x=>x==='destroy:row1').length);a.target.remove();});
import {bindViewDefinition,resolveView} from '../src/lib/application/view-binding.js';
it('reuses keyed and nested typed slot tokens rather than allocating discarded ChildViews each turn',()=>{const store=createStore({initialState:initial(0),...composition,dependencies:{step:1,trace:[]}});const bound=bindViewDefinition(store,rootViews);const spy=vi.spyOn(composition,'bind');try{resolveView(bound.rows);const first=spy.mock.results.map(result=>result.value);spy.mockClear();store.dispatch({type:'reorder'});resolveView(bound.rows);const second=spy.mock.results.map(result=>result.value);expect(second[0]).toBe(first[1]);expect(second[1]).toBe(first[0]);spy.mockClear();const workspace=resolveView(bound.workspace)[0]!;resolveView(workspace.views.editor!);const old=spy.mock.results.at(-1)!.value;spy.mockClear();resolveView(workspace.views.editor!);expect(spy.mock.results.at(-1)!.value).toBe(old);}finally{spy.mockRestore();store.destroy();}});
it('unmounts optional absence and mounts reopening with a new captured owner',async()=>{const a=setup();await tick();const old=captured.find(view=>view.state?.name==='editor')!;a.app.store.dispatch({type:'close'});await tick();expect(a.target.querySelector('[data-workspace]')).toBeNull();expect(events.filter(x=>x==='destroy:editor')).toHaveLength(1);a.app.store.dispatch({type:'open'});await tick();expect(leafNode(a.target,'editor').textContent).toBe('00');old.dispatch({type:'increment'});expect(leafNode(a.target,'editor').textContent).toBe('00');expect(events.filter(x=>x==='mount:editor')).toHaveLength(2);await unmount(a.component);a.target.remove();});
it('keeps numeric negative-zero keys distinct in the bounded token cache',()=>{const state=initial(0);state.rows=[{id:0,state:{name:'positive',count:0}},{id:-0,state:{name:'negative',count:0}}];const store=createStore({initialState:state,...composition,dependencies:{step:3,trace:[]}});const bound=bindViewDefinition(store,rootViews);const rows=resolveView(bound.rows);expect(rows).toHaveLength(2);expect(rows[0]!.key).not.toBe(rows[1]!.key);rows[1]!.store.dispatch({type:'increment'});expect(store.state.rows.map(row=>row.state.count)).toEqual([0,3]);store.destroy();});
it('unmounts raw managed feature views when their externally owned root is destroyed',async()=>{const target=document.createElement('div');document.body.append(target);const store=createStore({initialState:initial(0),...composition,dependencies:{step:1,trace:[]}});const component=mount(Raw,{target,props:{store}});await tick();expect(target.querySelectorAll('[data-leaf]')).toHaveLength(3);store.destroy();await tick();expect(target.querySelectorAll('[data-leaf]')).toHaveLength(0);await unmount(component);target.remove();});

it('retained root outlet descriptors stop when their application owner is destroyed',async()=>{const target=document.createElement('div');const extra=document.createElement('div');document.body.append(target,extra);let view!:WorkspaceView;const component=mount(Fixture,{target,props:{dependencies:{step:1,trace:[]},onWorkspace:value=>view=value}});await tick();expect(resolveView(view)).toHaveLength(1);expect(()=>mountView(view,extra)).toThrow('requires its declared FeatureViews layout');await unmount(component);await tick();expect(resolveView(view)).toEqual([]);expect(extra.querySelector('[data-leaf]')).toBeNull();target.remove();extra.remove();});
