import {targetFor,type TargetRegistry} from '../src/lib/application/renderer/target-registry.js';import {rowsSlot} from './fixtures/FeatureViewsModel.js';
import {expectConsole} from './helpers/console.js';
import {it,expect,vi,beforeEach,afterEach} from 'vitest';import {mount,unmount,tick} from 'svelte';import App from './fixtures/PlacementApp.svelte';import Boundary from './fixtures/PlacementBoundary.svelte';import type {ApplicationInstance} from '../src/lib/application/index.js';import {captured,type Root,type Action} from './fixtures/FeatureViewsModel.js';
function setup(missing=false,duplicate=false,repeat=false,headless=false){captured.length=0;const target=document.createElement('div');document.body.append(target);const trace:string[]=[];let app!:ApplicationInstance<Root,Action>;let registry!:TargetRegistry;const component=mount(Boundary,{target,props:{missing,duplicate,repeat,headless,dependencies:{step:1,trace},onApp:value=>app=value,onRegistry:value=>registry=value}});return{target,trace,get app(){return app;},get registry(){return registry;},component,async finish(){await unmount(component);target.remove();}};}
it('rejects missing initial placement before external startup, while headless requires no outlet',async()=>{const missing=setup(true);await tick();expect(missing.target.querySelector('[data-error]')?.textContent).toContain('Missing FeatureOutlet');expect(missing.trace).not.toContain('started');await missing.finish();const correct=setup();await tick();expect(correct.trace).toContain('started');expect(correct.target.querySelector('[data-error]')).toBeNull();await correct.finish();});
it('rejects duplicate same-handle placements before startup',async()=>{const a=setup(false,true);await tick();expect(a.target.querySelector('[data-error]')?.textContent).toContain('Duplicate FeatureOutlet');expect(a.trace).not.toContain('started');await a.finish();});
it('captures only inert outgoing HTML while the keyed live child retires',async()=>{captured.length=0;const a=setup();await tick();const old=captured.find(view=>view.state?.name==='row1')!;a.app.store.dispatch({type:'removeRow'});expect(old.state).toBeUndefined();await tick();expect(a.target.querySelector('[data-leaf="row1"]')).toBeNull();const layers=[...document.body.children].filter(node=>node.getAttribute('aria-hidden')==='true');expect(layers).toHaveLength(1);expect(layers[0]?.textContent).toBe('10');expect(layers[0]?.querySelector('button,[id]')).toBeNull();const animations=layers[0]!.getAnimations({subtree:true});expect(animations).toHaveLength(1);for(const animation of animations)animation.finish();await Promise.all(animations.map(animation=>animation.finished));await tick();expect(layers[0]?.childNodes).toHaveLength(0);expect(document.body.contains(layers[0]!)).toBe(false);await a.finish();expect(document.body.contains(layers[0]!)).toBe(false);});

it('dynamic missing placement fails closed at its exact root after reconciliation',async()=>{const a=setup();await tick();const old=captured.find(view=>view.state?.name==='row1')!;expectConsole('error');(a.target.querySelector('[data-hide]') as HTMLButtonElement).click();await tick();await tick();expect(old.state).toBeUndefined();await vi.waitFor(()=>expect(a.target.querySelectorAll('[data-leaf]')).toHaveLength(0));await a.finish();});

let media:{mockRestore():void}|undefined;
beforeEach(()=>{const original=window.matchMedia.bind(window);media=vi.spyOn(window,'matchMedia').mockImplementation(query=>{const result=original(query);if(query==='(prefers-reduced-motion: reduce)')Object.defineProperty(result,'matches',{value:false,configurable:true});return result;});});
afterEach(()=>media?.mockRestore());
it('coalesces a keyed replace batch and revokes old run on another accepted replacement',async()=>{const a=setup();await tick();a.app.store.dispatch({type:'removeRow'});a.app.store.dispatch({type:'addRow'});a.app.store.dispatch({type:'replaceRow'});await tick();const layer=[...document.body.children].find(node=>node.getAttribute('aria-hidden')==='true')!;expect(layer.children).toHaveLength(1);const previous=layer.firstElementChild!;const animation=previous.getAnimations()[0]!;a.app.store.dispatch({type:'replaceRow'});await tick();expect(previous.isConnected).toBe(false);expect(animation.playState).toBe('idle');const successor=[...document.body.children].find(node=>node.getAttribute('aria-hidden')==='true')!;expect(successor.children).toHaveLength(1);await a.finish();expect(layer.isConnected).toBe(false);});

it('skips a surface whose active property lease was retired by logical child cleanup',async()=>{const a=setup();await tick();const view=captured.find(view=>view.state?.name==='row1')!;const node=a.target.querySelector<HTMLElement>('[data-leaf="row1"]')!;const handle=a.registry.register(view,targetFor(rowsSlot.at(1),['opacity']),node,{opacity:'1'});const lease=handle.lease('opacity');lease.write('0.4');expect(node.style.opacity).toBe('0.4');a.app.store.dispatch({type:'removeRow'});expect(lease.live).toBe(false);await tick();expect([...document.body.children].filter(node=>node.getAttribute('aria-hidden')==='true')).toHaveLength(0);expect(a.target.querySelector('[data-leaf="row1"]')).toBeNull();await a.finish();});

it('rejects a second layout for the same canonical root owner even with freshly bound handles',async()=>{const a=setup(false,false,true);await tick();expect(a.target.querySelector('[data-error]')?.textContent).toContain('Duplicate rendering layout');expect(a.trace).not.toContain('started');await a.finish();});
it('dynamic invalidation cleans only the owning root',async()=>{const a=setup();await tick();const old=captured.find(view=>view.state?.name==='editor')!;const b=setup();await tick();expectConsole('error');(a.target.querySelector('[data-hide]') as HTMLButtonElement).click();await vi.waitFor(()=>expect(old.state).toBeUndefined());expect(b.app.store.state.workspace?.editor?.count).toBe(0);(b.target.querySelector('[data-leaf="editor"] [data-action="increment"]') as HTMLButtonElement).click();await tick();expect(b.app.store.state.workspace?.editor?.count).toBe(1);await a.finish();await b.finish();});
it('a lease released before logical retirement permits capture of its accepted stable pose',async()=>{const a=setup();await tick();const view=captured.find(view=>view.state?.name==='row1')!;const node=a.target.querySelector<HTMLElement>('[data-leaf="row1"]')!;const handle=a.registry.register(view,targetFor(rowsSlot.at(1),['opacity']),node,{opacity:'0.8'});const lease=handle.lease('opacity');lease.write('0.4');lease.release();a.app.store.dispatch({type:'removeRow'});await tick();const layer=[...document.body.children].find(node=>node.getAttribute('aria-hidden')==='true')!;expect(layer.children).toHaveLength(1);expect((layer.firstElementChild!.firstElementChild as HTMLElement).style.opacity).toBe('0.8');await a.finish();});
it('skips reduced-motion exits while retiring the live feature immediately',async()=>{media?.mockRestore();const original=window.matchMedia.bind(window);media=vi.spyOn(window,'matchMedia').mockImplementation(query=>{const result=original(query);if(query==='(prefers-reduced-motion: reduce)')Object.defineProperty(result,'matches',{value:true});return result;});const a=setup();await tick();a.app.store.dispatch({type:'removeRow'});await tick();expect(a.target.querySelector('[data-leaf="row1"]')).toBeNull();expect([...document.body.children].filter(node=>node.getAttribute('aria-hidden')==='true')).toHaveLength(0);await a.finish();});
it('the run deadline releases visual retention even when native completion never arrives',async()=>{const a=setup();await tick();vi.useFakeTimers();const native=HTMLElement.prototype.animate;let animation:Animation|undefined;const spy=vi.spyOn(HTMLElement.prototype,'animate').mockImplementation(function(this:HTMLElement,keyframes,options){animation=native.call(this,keyframes,options);Object.defineProperty(animation,'finished',{value:new Promise<Animation>(()=>{})});return animation;});try{a.app.store.dispatch({type:'removeRow'});await tick();const layer=[...document.body.children].find(node=>node.getAttribute('aria-hidden')==='true')!;expect(layer.children).toHaveLength(1);await vi.advanceTimersByTimeAsync(299);expect(layer.children).toHaveLength(1);await vi.advanceTimersByTimeAsync(1);expect(layer.children).toHaveLength(0);expect(animation?.playState).toBe('idle');}finally{spy.mockRestore();vi.useRealTimers();await a.finish();}});
it('preference changes supersede active playback and release its outgoing snapshot',async()=>{media?.mockRestore();const original=window.matchMedia.bind(window);const preference=original('(prefers-reduced-motion: reduce)');let reduced=false;Object.defineProperty(preference,'matches',{get:()=>reduced});media=vi.spyOn(window,'matchMedia').mockImplementation(query=>query==='(prefers-reduced-motion: reduce)'?preference:original(query));const a=setup();await tick();a.app.store.dispatch({type:'removeRow'});await tick();const layer=[...document.body.children].find(node=>node.getAttribute('aria-hidden')==='true')!;const animation=layer.getAnimations({subtree:true})[0]!;reduced=true;preference.dispatchEvent(new Event('change'));await tick();expect(layer.children).toHaveLength(0);expect(animation.playState).toBe('idle');expect(a.app.store.state.rows.map(row=>row.id)).toEqual([2]);await a.finish();});
import Raw from './fixtures/PlacementRaw.svelte';import {createStore} from '../src/lib/store.svelte.js';import {composition,initial} from './fixtures/FeatureViewsModel.js';
it('invalid borrowed raw rendering closes its scope without destroying the external root',async()=>{const target=document.createElement('div');document.body.append(target);const store=createStore({initialState:initial(0),...composition,dependencies:{step:1,trace:[]}});const component=mount(Raw,{target,props:{store}});await tick();expectConsole('error');(target.querySelector('[data-hide]') as HTMLButtonElement).click();await vi.waitFor(()=>expect(target.querySelectorAll('[data-leaf]')).toHaveLength(0));store.dispatch(rowsSlot.at(2).wrap({type:'increment'}));expect(store.state.rows[1]?.state.count).toBe(3);await unmount(component);store.destroy();target.remove();});

it('allows one outlet to relocate across a reconciled conditional layout',async()=>{const a=setup();await tick();(a.target.querySelector('[data-move]') as HTMLButtonElement).click();await tick();expect(a.target.querySelector('[data-location="second"] [data-leaf="row1"]')).not.toBeNull();expect(a.target.querySelector('[data-error]')).toBeNull();expect(a.app.store.state.rows).toHaveLength(2);await a.finish();});

it('rejects an explicit outlet for a declared headless feature before startup',async()=>{const a=setup(false,false,false,true);await tick();expect(a.target.querySelector('[data-error]')?.textContent).toContain('Headless feature');expect(a.trace).not.toContain('started');await a.finish();});
it('rejects sustained duplicate outlets after reconciliation and retires the owning root',async()=>{const a=setup();await tick();const old=captured.find(view=>view.state?.name==='row1')!;expectConsole('error');(a.target.querySelector('[data-duplicate]') as HTMLButtonElement).click();await vi.waitFor(()=>expect(old.state).toBeUndefined());await vi.waitFor(()=>expect(a.target.querySelectorAll('[data-leaf]')).toHaveLength(0));await a.finish();});
it('lease release invokes teardown immediately, independently of later feature retirement',async()=>{const a=setup();await tick();const view=captured.find(view=>view.state?.name==='row1')!;const node=a.target.querySelector('[data-leaf="row1"]') as HTMLElement;const handle=a.registry.register(view,targetFor(rowsSlot.at(1),['opacity']),node,{opacity:'1'});const cleanup=vi.fn();const lease=handle.lease('opacity',cleanup);lease.release();expect(cleanup).toHaveBeenCalledTimes(1);expect(view.state).toBeDefined();a.app.store.dispatch({type:'removeRow'});await tick();expect(cleanup).toHaveBeenCalledTimes(1);await a.finish();});

it('a retired ancestor lease skips its cancellation turn but not a later unrelated exit',async()=>{const a=setup();await tick();const first=captured.find(view=>view.state?.name==='row1')!;const ancestor=a.target.querySelector('[data-location="first"]') as HTMLElement;const handle=a.registry.register(first,targetFor(rowsSlot.at(1),['opacity']),ancestor,{opacity:'1'});handle.lease('opacity').write('0.4');a.app.store.dispatch({type:'removeRow'});await tick();expect([...document.body.children].filter(node=>node.getAttribute('aria-hidden')==='true')).toHaveLength(0);a.app.store.dispatch({type:'addRow'});await tick();a.app.store.dispatch({type:'removeRow'});await tick();const layer=[...document.body.children].find(node=>node.getAttribute('aria-hidden')==='true');expect(layer?.children).toHaveLength(1);await a.finish();});

it('a second borrowed layout cannot claim an already mounted canonical owner',async()=>{const first=document.createElement('div'),second=document.createElement('div');document.body.append(first,second);const store=createStore({initialState:initial(0),...composition,dependencies:{step:1,trace:[]}});const a=mount(Raw,{target:first,props:{store}});await tick();expectConsole('error',2);const b=mount(Raw,{target:second,props:{store}});await vi.waitFor(()=>expect(second.querySelectorAll('[data-leaf]')).toHaveLength(0));expect(first.querySelectorAll('[data-leaf]').length).toBeGreaterThan(0);store.dispatch(rowsSlot.at(2).wrap({type:'increment'}));expect(store.state.rows[1]?.state.count).toBe(3);await unmount(b);await unmount(a);store.destroy();first.remove();second.remove();});

it('a dynamically mounted layout with no outlets fails its owned root without an application error boundary',async()=>{const target=document.createElement('div');document.body.append(target);let app!:ApplicationInstance<Root,Action>;const component=mount(App,{target,props:{dependencies:{step:1,trace:[]},onApp:value=>app=value}});await tick();const old=captured.find(view=>view.state?.name==='row1')!;expectConsole('error');(target.querySelector('[data-layout]') as HTMLButtonElement).click();await vi.waitFor(()=>expect(old.state).toBeUndefined());await vi.waitFor(()=>expect(target.querySelectorAll('[data-leaf]')).toHaveLength(0));await unmount(component);target.remove();});

it('rejects unsupported mixed-document capture batch with an explicit diagnostic and snapshot cleanup',async()=>{
 const iframe=document.createElement('iframe');
 document.body.appendChild(iframe);
 const topPreference={matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()};
 const framePreference={matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()};
 media?.mockRestore();
 media=vi.spyOn(window,'matchMedia').mockReturnValue(topPreference as unknown as MediaQueryList);
 const frameSpy=vi.spyOn(iframe.contentWindow!,'matchMedia').mockReturnValue(framePreference as unknown as MediaQueryList);
 try{
  const a=setup();await tick();
  const errors=expectConsole('error');
  const iframeDoc=iframe.contentDocument!;
  const topNode=a.target.querySelector<HTMLElement>('[data-leaf="row1"]')!;
  const iframeNode=iframeDoc.createElement('div');
  iframeNode.textContent='iframe leaf';
  iframeDoc.body.appendChild(iframeNode);
  const channel=new (await import('../src/lib/application/renderer/capture-channel.js')).CaptureChannel(a.registry);
  const regTop=channel.register({id:'top-surface'},()=>topNode);
  const regIframe=channel.register({id:'iframe-surface'},()=>iframeNode);
  channel.prepare([]);
  channel.rendered();
  await tick();
  const layers=[...document.body.children,...iframeDoc.body.children].filter(node=>node.getAttribute('aria-hidden')==='true');
  expect(layers).toHaveLength(0);
  expect(topPreference.addEventListener).not.toHaveBeenCalled();
  expect(framePreference.addEventListener).not.toHaveBeenCalled();
  expect(errors.flat().some(value=>value instanceof Error&&value.message==='Mixed-document capture is unsupported')).toBe(true);
  regTop();regIframe();channel.dispose();
  await a.finish();
 }finally{
  frameSpy.mockRestore();
  iframe.remove();
 }
});
