import {describe,it,expect,vi} from 'vitest';
import {mount,unmount,flushSync} from 'svelte';
import {userEvent} from 'vitest/browser';
import PublicAssembly from './test-components/PublicAssembly.svelte';
import type {Store} from '../src/lib/types.js';
import type {AccordionState,AccordionAction} from '../src/lib/components/ui/accordion/accordion.types.js';
function setup(){const target=document.createElement('div');document.body.appendChild(target);let store!:Store<AccordionState,AccordionAction>;const expanded=vi.fn();const component=mount(PublicAssembly,{target,props:{ready:s=>store=s,expanded}});flushSync();return {target,component,store,expanded,async cleanup(){await unmount(component);target.remove();}};}
describe('public assembly contracts',()=>{
 it('B002-001 renders and updates nested object and array fields',async()=>{const h=setup();try{expect(h.target.querySelector('[data-value="name"]')?.textContent).toBe('Ada');expect(h.target.querySelector('[data-value="array"]')?.textContent).toBe('First');h.component.editNested();flushSync();expect(h.target.querySelector('[data-value="name"]')?.textContent).toBe('Grace');expect(h.target.querySelector('[data-value="array"]')?.textContent).toBe('Changed');}finally{await h.cleanup();}});
 it('B003-1 renders declarative content, callbacks and disabled controls',async()=>{const h=setup();try{const trigger=h.target.querySelector('[data-declarative] button') as HTMLButtonElement;expect(trigger?.textContent).toContain('Declared');expect(h.target.querySelector('[data-declarative] [role="region"]')?.textContent).toContain('Declared body');await userEvent.click(trigger);flushSync();expect(trigger.getAttribute('aria-expanded')).toBe('true');expect(h.expanded).toHaveBeenCalledExactlyOnceWith('shared');expect((h.target.querySelector('[data-declarative] button[disabled]') as HTMLButtonElement).disabled).toBe(true);h.component.replaceItems([{id:'new',title:'Replacement',content:'New body'}]);flushSync();expect(h.target.querySelector('[data-declarative]')?.textContent).toContain('Replacement');expect(h.target.querySelector('[data-declarative]')?.textContent).not.toContain('Declared');}finally{await h.cleanup();}});
 it('B003-2 registers composed items for expand-all and unregisters removed children',async()=>{const h=setup();try{expect(h.store.state.items.map(x=>x.id)).toEqual(['first','second','blocked']);h.store.dispatch({type:'allExpanded'});flushSync();expect(h.store.state.expandedIds).toEqual(['first','second']);h.component.setSecond(false);flushSync();expect(h.store.state.items.map(x=>x.id)).toEqual(['first','blocked']);expect(h.store.state.expandedIds).toEqual(['first']);h.component.changeId('renamed');flushSync();expect(h.store.state.items.map(x=>x.id)).toEqual(['blocked','renamed']);expect(h.store.state.expandedIds).toEqual([]);h.store.dispatch({type:'allExpanded'});expect(h.store.state.expandedIds).toEqual(['renamed']);}finally{await h.cleanup();}});
 it('disabled updates preserve expansion and update reducer decisions',async()=>{const h=setup();try{expect(h.store.state.expandedIds).toEqual(['first']);h.component.setDisabled(true);flushSync();expect(h.store.state.expandedIds).toEqual(['first']);expect(h.store.state.items.find(x=>x.id==='first')?.disabled).toBe(true);h.store.dispatch({type:'allExpanded'});expect(h.store.state.expandedIds).toEqual(['second']);h.component.setDisabled(false);flushSync();h.store.dispatch({type:'allExpanded'});expect(h.store.state.expandedIds).toEqual(['first','second']);}finally{await h.cleanup();}});
 it('B003-4 ARIA pairs resolve uniquely across repeated business IDs',async()=>{const h=setup();try{const regions=[...h.target.querySelectorAll('[role="region"]')];expect(regions.length).toBeGreaterThan(3);const ids=regions.flatMap(region=>{const label=region.getAttribute('aria-labelledby');expect(label).toBeTruthy();const trigger=document.getElementById(label!);expect(trigger?.getAttribute('aria-controls')).toBe(region.id);return [region.id,label!];});expect(new Set(ids).size).toBe(ids.length);}finally{await h.cleanup();}});
 it('explicit snippets take precedence over declarative fallback',async()=>{const h=setup();try{expect(h.target.querySelector('[data-precedence]')?.textContent).toContain('Custom snippet');expect(h.target.querySelector('[data-precedence]')?.textContent).not.toContain('Must not render');}finally{await h.cleanup();}});
});
