import {run, inReducer, module, core} from './harness.mjs';
const svelte = (script, tpl) => ({'App.svelte': `<script lang="ts">\n${script}\n</script>\n${tpl}\n`});
run([
  ['S1 control reject(state)', inReducer(``, `new Promise((res, rej) => { rej(state); });`)],
  ['S1 mixed settle state', inReducer(``, `new Promise((res, rej) => { const f = Math.random() > 0.5 ? rej : res; f(state); });`)],
  ['S1b mixed settle other order', inReducer(``, `new Promise((res, rej) => { const f = Math.random() > 0.5 ? res : rej; f(state); });`)],
  ['S2 mixed thenable', module(`export const p = new Promise((res, rej) => { const f = Math.random() > 0.5 ? res : rej; f({ then(cb: any) { cb(1); } }); });\n`)],
  ['T1 settle to template DOM handler', svelte(`let fire: any; const p = new Promise(r => { fire = r; }); async function go() { const ev: any = await p; ev.target.textContent = 'x'; }`, `<button onclick={fire}>x</button>`)],
  ['T1c control handler direct', svelte(`async function go(ev: any) { ev.target.textContent = 'x'; }`, `<button onclick={go}>x</button>`)],
  ['T2 settle to ext component prop', {'App.svelte': `<script lang="ts">\nimport {Widget} from 'ext';\nlet fire: any; const p = new Promise(r => { fire = r; });\n</script>\n<Widget onDone={fire} />\n`}],
  ['T3 settle via bind directive', svelte(`let fire: any = $state(); const p = new Promise(r => { fire = r; });`, `<input bind:value={fire} />`)],
  ['R1 Reflect.construct', module(`export async function go() { const v: any = await Reflect.construct(Promise, [(r: any) => r(window.location)]); v.href = '/x'; }\n`)],
  ['R2 window.Promise', module(`export async function go() { const v: any = await new window.Promise((r: any) => r(window.location)); v.href = '/x'; }\n`)],
  ['R3 globalThis.Promise', module(`export async function go() { const v: any = await new globalThis.Promise((r: any) => r(window.location)); v.href = '/x'; }\n`)],
  ['R4 alias P=Promise', module(`const P = Promise;\nexport async function go() { const v: any = await new P((r: any) => r(window.location)); v.href = '/x'; }\n`)],
  ['C1 toString throw in executor', module(`const o = { toString() { throw window.location; } };\nexport async function go() { try { await new Promise(() => { const s = \`\${o}\`; }); } catch (e: any) { e.href = '/x'; } }\n`)],
  ['C1b base parity plain', module(`const o = { toString() { throw window.location; } };\nexport function go() { try { const s = \`\${o}\`; } catch (e: any) { e.href = '/x'; } }\n`)],
  ['E1 settle via getter alias', module(`import {sink} from 'ext';\nexport const p = new Promise(r => { const o = { get r() { return r; } }; sink(o); });\n`)],
  ['E2 settle Map.set', module(`const m = new Map();\nexport const p = new Promise(r => { m.set('r', r); });\nexport {m};\n`)],
  ['E3 settle ns export to ext', {'entry.ts': `import {sink} from 'ext';\nimport * as A from './a';\nsink(A);\n`, 'a.ts': `export let fire: any;\nexport const p = new Promise(r => { fire = r; });\n`}],
  ['E4 settle via Object.assign', module(`const t: any = {};\nexport const p = new Promise(r => { Object.assign(t, {r}); });\nexport {t};\n`)],
  ['E5 settle via closure returned', module(`export function mk() { let f: any; new Promise(r => { f = r; }); return () => f; }\n`)],
  ['E6 settle in executor default param', module(`export const p = new Promise((r, j, x = r) => { });\n`)],
  ['E7 settle destructured rest array', module(`import {sink} from 'ext';\nexport const p = new Promise((...[a]: any[]) => { sink(a); });\n`)],
  ['E8 settle passed to local that stores on heap', module(`const h: any = {};\nfunction keep(f: any) { h.f = f; }\nexport const p = new Promise(r => keep(r));\nexport {h};\n`)],
  ['E9 resolve via queueMicrotask closure data', module(`export const p = new Promise(r => queueMicrotask(() => r({ok: 1})));\n`)],
  ['E10 resolve value with state from store', inReducer(``, `new Promise(r => r(state));`)],
  ['E11 resolve heap w/ later fn write', module(`const d: any = {n: 1};\nexport const p = new Promise(r => r(d));\nd.f = () => history.back();\n`)],
  ['E12 executor returns authority', module(`export const p = new Promise(() => window.location);\n`)],
  ['E13 settle in tagged template', module(`function tag(s: any, f: any) { return f; }\nexport const p = new Promise(r => { tag\`x\${r}\`; });\n`)],
  ['E14 executor this', module(`export const p = new Promise(function (this: any, r) { this.r = r; });\n`)],
  ['E15 settle to $state', svelte(`let s: any = $state(null); const p = new Promise(r => { s = r; });`, `<p>x</p>`)],
  ['E16 settle via spread call array', module(`function call(...fs: any[]) { fs[0](window.location); }\nexport async function go() { const v: any = await new Promise(r => call(r)); v.href = '/x'; }\n`)],
  ['E17 arguments forwarding local', module(`function call(this: any) { (arguments as any)[0](window.location); }\nexport async function go() { const v: any = await new Promise(r => call(r)); v.href = '/x'; }\n`)],
  ['E18 bound local wrapper', module(`function call(f: any, v: any) { f(v); }\nexport async function go() { const b = call.bind(null); const v: any = await new Promise(r => b(r, window.location)); v.href = '/x'; }\n`)],
  ['E19 apply tuple', module(`function call(f: any, v: any) { f(v); }\nexport async function go() { const v: any = await new Promise(r => call.apply(null, [r, window.location])); v.href = '/x'; }\n`)],
  ['E20 settle into class field ctor', module(`class K { f: any; constructor(f: any) { this.f = f; } }\nexport const k: any[] = [];\nexport const p = new Promise(r => { k.push(new K(r)); });\n`)],
  ['E21 await resolve result', module(`export async function go() { const x = await new Promise(r => { const y = r(1); }); }\n`)],
  ['E22 throw from getter-called fn', module(`function boom(): any { throw window.history; }\nexport async function go() { try { await new Promise(() => { const o = { m: boom }; o.m(); }); } catch (e: any) { e.back(); } }\n`)],
  ['E23 throw via callback to local HOF held in heap', module(`const api = { run(f: any) { f(); } };\nexport const p = new Promise(() => { api.run(() => { throw window.location; }); });\n`)],
  ['E24 throw in fn returned by call', module(`function mk() { return () => { throw window.location; }; }\nexport const p = new Promise(() => { mk()(); });\n`)],
  ['E25 throw via for-of iterator', module(`const it = { *[Symbol.iterator]() { throw window.location; } };\nexport const p = new Promise(() => { for (const x of it as any) {} });\n`)],
]);
