import{afterEach,it,expect}from'vitest';
import{animateModalIn,animateModalOut,animateSheetIn,animateSheetOut,animateDrawerIn,animateDrawerOut,animateAlertIn,animateAlertOut,animateBackdropIn,animateBackdropOut}from'../../src/lib/animation/animate';
type Run=(element:HTMLElement,signal:AbortSignal)=>Promise<void>;
const runs:Array<[string,Run]>=[['modal-in',(e,s)=>animateModalIn(e,undefined,s)],['modal-out',(e,s)=>animateModalOut(e,undefined,s)],['sheet-in',(e,s)=>animateSheetIn(e,'bottom',undefined,s)],['sheet-out',(e,s)=>animateSheetOut(e,'left',undefined,s)],['drawer-in',(e,s)=>animateDrawerIn(e,'right',undefined,s)],['drawer-out',(e,s)=>animateDrawerOut(e,'left',undefined,s)],['alert-in',(e,s)=>animateAlertIn(e,undefined,s)],['alert-out',(e,s)=>animateAlertOut(e,undefined,s)],['backdrop-in',animateBackdropIn],['backdrop-out',animateBackdropOut]];
const elements:HTMLElement[]=[];afterEach(()=>{for(const e of elements.splice(0)){e.getAnimations().forEach(a=>a.cancel());e.remove();}});
function element(){const e=document.createElement('div');e.style.cssText='position:fixed;left:100px;top:100px;width:80px;height:80px;opacity:.4';document.body.append(e);elements.push(e);return e;}
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
it.each(runs)('%s pre-aborted owner starts no native animation or style write',async(_name,run)=>{const e=element();const owner=new AbortController();owner.abort();const promise=run(e,owner.signal);expect(e.getAnimations()).toHaveLength(0);await promise;expect(e.style.opacity).toBe('0.4');});
it.each(runs)('%s abort settles paused playback within the next rendering boundary',async(_name,run)=>{const e=element();const owner=new AbortController();const promise=run(e,owner.signal);await frame();e.getAnimations().forEach(a=>a.pause());owner.abort();expect(await Promise.race([promise.then(()=>true),frame().then(frame).then(()=>false)])).toBe(true);expect(e.getAnimations().filter(a=>a.playState==='running'||a.playState==='paused')).toHaveLength(0);});
