import{afterEach,it,expect,vi}from'vitest';
import{mount,unmount,flushSync}from'svelte';
import{createStore}from'@composable-svelte/core';
import{nodeCanvasReducer}from'../src/lib/node-canvas/reducer';
import{createInitialNodeCanvasState,type NodeCanvasAction,type NodeCanvasState}from'../src/lib/node-canvas/types';
import GraphBoundaryHarness from './test-components/GraphBoundaryHarness.svelte';
import{graphProbe}from'./test-components/graph-probe';
const cleanups:Array<()=>void>=[];afterEach(()=>{for(const f of cleanups.splice(0))f();});
async function setup(){const state=createInitialNodeCanvasState({nodes:{a:{id:'a',type:'operation',position:{x:100,y:100},data:{}},b:{id:'b',type:'operation',position:{x:300,y:100},data:{}}}});state.selectedNodes=new Set(['a','b']);const store=createStore<NodeCanvasState,NodeCanvasAction>({initialState:state,reducer:nodeCanvasReducer,dependencies:{}});const target=document.createElement('div');document.body.append(target);const component=mount(GraphBoundaryHarness,{target,props:{store}});flushSync();cleanups.push(()=>{void unmount(component);store.destroy();target.remove();});await vi.waitFor(()=>{expect(graphProbe.getNode?.('a')).toBeDefined();expect(target.querySelector('[data-id="a"]')?.getBoundingClientRect().width).toBeGreaterThan(0);});return{store,target};}
it('projected selected node identity remains stable across unrelated state updates',async()=>{const{store}=await setup();const first=graphProbe.getNode!('a');expect(first?.selected).toBe(true);expect(first).not.toBe(store.state.nodes.a);for(let i=0;i<4;i++){store.dispatch({type:'setGridSize',size:11+i});flushSync();expect(graphProbe.getNode!('a')).toBe(first);}store.dispatch({type:'moveNode',nodeId:'a',position:{x:120,y:100}});flushSync();expect(graphProbe.getNode!('a')).not.toBe(first);});
it('dragging a selected node persists movement for every selected group member',async()=>{const{store,target}=await setup();const element=target.querySelector<HTMLElement>('[data-id="a"]')!;const rect=element.getBoundingClientRect();const start={clientX:rect.x+20,clientY:rect.y+20};element.dispatchEvent(new MouseEvent('mousedown',{...start,bubbles:true,cancelable:true,buttons:1,button:0,view:window}));window.dispatchEvent(new MouseEvent('mousemove',{clientX:start.clientX+50,clientY:start.clientY+30,bubbles:true,cancelable:true,buttons:1,view:window}));window.dispatchEvent(new MouseEvent('mousemove',{clientX:start.clientX+80,clientY:start.clientY+50,bubbles:true,cancelable:true,buttons:1,view:window}));window.dispatchEvent(new MouseEvent('mouseup',{clientX:start.clientX+80,clientY:start.clientY+50,bubbles:true,cancelable:true,button:0,view:window}));flushSync();await vi.waitFor(()=>expect(store.state.nodes.a!.position.x).not.toBe(100));const dx=store.state.nodes.a!.position.x-100;const dy=store.state.nodes.a!.position.y-100;expect(store.state.nodes.b!.position).toEqual({x:300+dx,y:100+dy});});
